#if !defined(__POSITION_CREATION_PORTFOLIO_TEST_H__) && defined(__TEST_MAIN__)
#define __POSITION_CREATION_PORTFOLIO_TEST_H__
#include "simulation/Simulation.h"

using namespace std;
using namespace events;
using namespace channel;
using namespace feed;
using namespace strategy;
using namespace broker;
using namespace portfolio;
using namespace journal;

namespace simulation {
    class PositionCreationPortfolio: public Portfolio {
        public:
            using Portfolio::Portfolio; 

            // `SignalEvent` is generated by `Strategy` and may trigger an `OrderEvent`.
            unique_ptr<Event> process_signal(const SignalEvent & event) override;

            // `FillEvent` is generated by `ExecutionHandler`. It contains the information needed to create or update positions.
            unique_ptr<Event> process_fill(const FillEvent & event) override;            
    };
}
#endif