#ifdef __TEST_MAIN__
#include "simulation/Simulation.h"
#include "PositionCreationPortfolio.h"

namespace simulation {
        // `SignalEvent` is generated by `Strategy` and may trigger an `OrderEvent`.
        unique_ptr<Event> PositionCreationPortfolio::process_signal(const SignalEvent & event) {
             return nullptr;
        }

        // `FillEvent` is generated by `ExecutionHandler`. It contains the information needed to create or update positions.
        unique_ptr<Event> PositionCreationPortfolio::process_fill(const FillEvent & event) {
            return nullptr;
        }
}

#endif