#include "Portfolio.h"

using namespace std;
using namespace events;

namespace portfolio {
    unique_ptr<Event> Portfolio::process_market(const MarketEvent & event) {
        vector<Signal> signals;

        for(const auto & [symbol, bar] : event.bars) {
            if(!bars_.contains(bar.symbol())) {
                bars_.emplace(bar.symbol(), vector<Bar>());
                bar_timestamps_.emplace(bar.symbol(), set<sys_seconds>());
            }

            vector<Bar> & bars = bars_.at(bar.symbol());
            set<sys_seconds> & bar_timestamps = bar_timestamps_.at(bar.symbol());

            if(!bar_timestamps.contains(bar.timestamp())) {
                bars.emplace_back(bar);
                bar_timestamps.emplace(bar.timestamp());
            }
        }

        return event.clone();
    }

    // `SignalEvent` is generated by `Strategy` and may trigger an `OrderEvent`.
    unique_ptr<Event> Portfolio::process_signal(const SignalEvent & event) {
        vector<Order> orders;

        for(const auto & signal : event.signals()) {
            if(positions_.contains(signal.symbol())) {
                auto order_result = create_order(signal);
                if(order_result.has_value()) {
                    const auto & order = order_result.value();
                    orders.emplace_back(order);
                }
            }
        }

        if(orders.size() > 0) {
            return make_unique<OrderEvent>(std::move(orders));
        } else {
            return make_unique<Event>(EventType::FETCH);
        }
    }

    unique_ptr<Event> Portfolio::process_event(const Event & event) {
        if(event.event_type == EventType::SIGNAL) {
            const SignalEvent & signal_event = static_cast<const SignalEvent &>(event);
            signal_count_++;
            return process_signal(signal_event);

        } else if(event.event_type == EventType::FILL) {
            const FillEvent & fill_event = static_cast<const FillEvent &>(event);
            fill_count_++;
            return process_fill(fill_event);

        } else if(event.event_type == EventType::MARKET) {
            const MarketEvent & market_event = static_cast<const MarketEvent &>(event);
            market_count_++;
            return process_market(market_event);
        }

        return nullptr;
    }

}