#ifndef __PORTFOLIO_H__
#define __PORTFOLIO_H__
#include <string>
#include <unordered_map>
#include "events/SignalEvent.h"
#include "events/FillEvent.h"
#include "events/LogEvent.h"
#include "events/MarketEvent.h"
#include "data/SignalDirection.h"
#include "events/EventProcessor.h"
#include "events/OrderEvent.h"
#include <mutex>
#include <set>

using namespace std;
using namespace events;

namespace portfolio {
    class Position {
        public:
         //Contains position and holding information.
            const string symbol;
            const sys_seconds timestamp;
            const int quantity;
            const SignalDirection direction;
            const double entry_price;
        private:
            double current_price_;
            int life_span_;
        public:
            inline Position(
                const string & symbol_, 
                const sys_seconds timestamp_, 
                int quantity_, 
                SignalDirection direction_, 
                double entry_price_
            ): symbol(symbol_), timestamp(timestamp_), quantity(quantity_), direction(direction_), entry_price(entry_price_), current_price_(entry_price_), life_span_(0) {

            }

            void update(double current_price_, int life_span_) {
                this->current_price_ = current_price_;
                this->life_span_ = life_span_;
            }

            inline double current_price() const {return current_price_;}
            inline int live_span() const {return life_span_;}

    };

    class Portfolio: public EventProcessor {
        private:
            unordered_map<string, Position> positions_;
            double cash_;
            double equity_;
            double commissions_;
            size_t signal_count_;
            size_t fill_count_;
            size_t market_count_;
            unordered_map<string, vector<Bar>> bars_;
            unordered_map<string, set<sys_seconds>> bar_timestamps_;
            
        public:
            inline Portfolio(): positions_({}), cash_(0), equity_(0), commissions_(0), signal_count_(0), fill_count_(0), market_count_(0), bars_({}),  bar_timestamps_({}){}

            virtual optional<Order> create_order(const Signal & signal) = 0;

            // `SignalEvent` is generated by `Strategy` and may trigger an `OrderEvent`.
            virtual unique_ptr<Event> process_signal(const SignalEvent & event);

            // `FillEvent` is generated by `Broker`. It contains the information needed to create or update positions.
            virtual unique_ptr<Event> process_fill(const FillEvent & event) = 0;

            // `MarketEvent` is generated by `Broker`. It just contain bar information.
            virtual unique_ptr<Event> process_market(const MarketEvent & event);

            // Called from events::Subscriber or events::Consumer
            unique_ptr<Event> process_event(const Event & event) override;

            inline size_t signal_count() const {return signal_count_;}

            inline size_t fill_count() const { return fill_count_;}

            inline double cash_value() const { return cash_; }

            inline double equity_value() const { return equity_; }
            
            inline double commissions_value() const { return commissions_; }
            
    };
}

#endif