#ifndef __PORTFOLIO_H__
#define __PORTFOLIO_H__
#include <string>
#include <unordered_map>
#include "events/SignalEvent.h"
#include "events/FillEvent.h"
#include "events/MarketEvent.h"
#include "events/LogEvent.h"
#include "data/SignalDirection.h"
#include "events/EventProcessor.h"
#include <mutex>

using namespace std;
using namespace events;

namespace portfolio {
    class Position {
        public:
         //Contains position and holding information.
            const string symbol;
            const sys_seconds timestamp;
            const int quantity;
            const SignalDirection direction;
            const double entry_price;
        private:
            double current_price_;
            int life_span_;
        public:
            inline Position(
                const string & symbol_, 
                const sys_seconds timestamp_, 
                int quantity_, 
                SignalDirection direction_, 
                double entry_price_
            ): symbol(symbol_), timestamp(timestamp_), quantity(quantity_), direction(direction_), entry_price(entry_price_), current_price_(entry_price_), life_span_(0) {

            }

            void update(double current_price_, int life_span_) {
                this->current_price_ = current_price_;
                this->life_span_ = life_span_;
            }

            inline double current_price() const {return current_price_;}
            inline int live_span() const {return life_span_;}

    };

    class Portfolio: public EventProcessor {
        private:
            unordered_map<string, Position> positions;
            double cash;
            double equity;
            double commissions;
            size_t signal_count_;
            size_t bar_count_;
            size_t fill_count_;
        public:
            inline Portfolio(): positions({}), cash(0), equity(0), commissions(0), signal_count_(0), bar_count_(0), fill_count_(0) {}

            // `MarketEvent` is generated by `DataHandler`. It contains bar data used to update the portfolio's equity and positions, and to close positions when necessary.
            virtual EventResponse process_bars(const unordered_map<string,Bar> & bars) = 0;

            // `SignalEvent` is generated by `Strategy` and may trigger an `OrderEvent`.
            virtual EventResponse process_signal(const SignalEvent & event) = 0;

            // `FillEvent` is generated by `ExecutionHandler`. It contains the information needed to create or update positions.
            virtual EventResponse process_fill(const FillEvent & event) = 0;

            // Called from events::Subscriber or events::Consumer
            EventResponse process_event(const Event & event) override;

            inline size_t signal_count() const {return signal_count_;}

            inline size_t bar_count() const { return bar_count_;}

            inline size_t fill_count() const { return fill_count_;}

            inline double cash_value() const { return cash; }

            inline double equity_value() const { return equity; }
            
            inline double commissions_value() const { return commissions; }
            
    };
}

#endif