#ifndef __TRADING_ENGINE_STRATEGY__
#define __TRADING_ENGINE_STRATEGY__
#include "trading-engine.h"
#include "trading-engine-datahandler.h"
#include <cstddef>
#include <map>

using namespace std;
using namespace trading::engine::datahandler;

namespace trading::engine::strategy {
    /*
    `Strategy` is an abstract base class providing an interface for
    all subsequent (inherited) strategy handling objects.

    The goal of a (derived) strategy object is to generate `Signal`
    objects for particular symbols based on the inputs of Bars (OHLC)
    generated by `DataHandler` object.

    This is designed to work both with historic and live data as
    the `Strategy` object is agnostic to where the data from,
    since it obtains the bar tuples fro a queue object.
    */
    class Strategy {
        protected:
            reference_wrapper<datahandler::DataHandler> datahandler_;
            [[maybe_unused]] Queue<unique_ptr<Event>> & events_;
        public:
            inline Strategy(reference_wrapper<datahandler::DataHandler> datahandler, Queue<unique_ptr<Event>> & events): datahandler_(datahandler), events_(events){}
            virtual void calculate_signals(MarketEvent & market_event) = 0;
            inline void calculate_signals(MarketEvent * market_event) {calculate_signals(*market_event);}
            virtual ~Strategy() = default;
    };

    enum class BOUGHT_STATUS {
        LONG,
        OUT
    };

    /*
    Carries out a basic Moving Average Crossover strategy with short/long simple weighted moving average. Default short/long windows
    are 100/400 respectively
    */
    class MovingAverageCrossStrategy: public Strategy {
        protected:
            size_t short_window_;
            size_t long_window_;
            map<string, BOUGHT_STATUS> bought_;

        public:
            MovingAverageCrossStrategy(
                reference_wrapper<datahandler::DataHandler> datahandler, // The Datahandler object that provides bar information.
                Queue<unique_ptr<Event>>  & events, // The event queue object.
                size_t short_window, // The short moving average lookback.
                size_t long_window // The long moving average lookback.
            );
            void calculate_signals(MarketEvent & market_event) override;
            virtual ~MovingAverageCrossStrategy() = default;
    };

};
#endif