#ifndef __TRADING_ENGINE_EXECUTION_HANDLER__
#define __TRADING_ENGINE_EXECUTION_HANDLER__
#include "trading-engine.h"
#include "trading-engine-portfolio.h"
#include <memory>

using namespace std;
using namespace timeseries::dataframe;
using namespace trading::engine;
using namespace trading::engine::portfolio;

namespace trading::engine::executionhandler {
    /*
    The `ExecutionHandler` abstract class handles the interaction
    between a set of order objects generated by a `Portfolio` and
    the ultimate set of `Fill` objects that actually occur in the
    market.

    The handlers can be used to subclass simulated brokerages
    or live brokerages, with identical interfaces. This 
    allows strategies to be backtested in a very similar manner
    to the live live trading engine.
    */
    class ExecutionHandler {
        public:
            /*
            Takes an `Order` event and executes it, producing
            a `Fill` event that gets placed onto the `Event` queue
            */
            virtual void execute_order(
                const OrderEvent & order_event // Contains the `OrderEvent` object with order information.
            ) = 0;

            virtual ~ExecutionHandler() = default;
    };

    /* 
    The simulated executionhandler simply converts all `Order`
    objects into their equivalent `Fill` objects automatically
    without latency, slippage or fill-ratio issues.

    This allows straightforward "first go" test of any strategy,
    before implementation with a more sophisticated execution
    handler.
    */
    class SimulationExecutionHandler: public ExecutionHandler {
        protected:
            unique_ptr<DataHandler> & datahandler_; // Must be in the same of scope of *this.
            Queue<unique_ptr<Event>> & events_; // Must be in the same of scope of *this.
        public:

            /* 
            Initializes the handler, setting the event queues up internally.
            */
            inline SimulationExecutionHandler(
                /* 
                Reference to datahablder; must always be in the same scope of `SimulationExecutionHandler`.
                */
                unique_ptr<DataHandler> & datahandler,
                
                /*
                The queue of `FillEvent` objects.
                Be aware that this class doesn't take ownership or copy
                `events` data; therefore `events` and hosting `SimulationExecutionHandler` 
                share the same scope.
                */
                Queue<unique_ptr<Event>> & events
            ): datahandler_(datahandler), events_(events){}

            /*
            Simple converts `OrderEvent` objects into `FillEvent` objects. naively,
            i.e. without any latency, slippage or fill ratio problems.
            */
            void execute_order(
                const OrderEvent & order_event // Contains an `OrderEvent` object with order information.
            ) override;
            
            virtual ~SimulationExecutionHandler() = default;

            static expected<unique_ptr<SimulationExecutionHandler>, TuxedoError> Create(unique_ptr<DataHandler> & datahandler, Queue<unique_ptr<Event>> & events);
    };
}

#endif