#ifndef __TRADING_ENGINE_STRATEGY__
#define __TRADING_ENGINE_STRATEGY__
#include "trading-engine.h"
#include "trading-engine-datahandler.h"

namespace trading::engine::strategy {
    /*
    `Strategy` is an abstract base class providing an interface for
    all subsequent (inherited) strategy handling objects.

    The goal of a (derived) strategy object is to generate `Signal`
    objects for particular symbols based on the inputs of Bars (OHLC)
    generated by `DataHandler` object.

    This is designed to work both with historic and live data as
    the `Strategy` object is agnostic to where the data from,
    since it obtains the bar tuples fro a queue object.
    */
    class Strategy {
        public:
            virtual void calculate_signals() = 0;
    };

};
#endif