#ifndef __TUXEDO_ERROR_H__
#define __TUXEDO_ERROR_H__

typedef enum TuxedoErrorEnum {
    NO_ERROR = 0,
    ERR_ARR_INDEX_OUT_OF_BOUNDS = 1,
    ERR_EMPTY_VECTOR = 2,
    ERR_INVALID_REGRESSION_TYPE = 3,
    ERR_NO_OBSERVATIONS = 4,
    ERR_SAMPLE_TOO_SMALL = 5,
    ERR_BAD_OUTPUT_DIMESNSIONS = 6,
    ERR_BAD_INPUT_DIMESNSIONS = 7,
    ERR_INCONSISTENT_ROW_LENGTH = 8,
    ERR_INVALID_DATA_FORMAT = 9,
    ERR_DATA_OUT_OF_RANGE = 10,
    ERR_LINEAR_REGRESSION_FAILED = 11,
    ERR_NOT_IMPLEMENTED = 12,
    ERR_NOT_INVERTIBLE_MATRIX = 13,
    ERR_NEGATIVE_LOG_ARG=14,
    ERR_CANT_CREATE_CLASSIFIER=15,
    ERR_CANT_OPEN_FILE=16,
    ERR_BAD_INPUT = 17
} TuxedoError;
#endif