#ifndef __ORDER_EVENT_H__
#define __ORDER_EVENT_H__
#include "Event.h"
#include "SignalEvent.h"
#include "data/Bar.h"
#include <string>
#include "data/Order.h"

using namespace std;

namespace events {
    /* 
    A concrete instruction to trade, generated by the `Portfolio`
    after it has processed a `SignalEvent` and applied its own logic for
    risk management and position sizing. `OrderEvent` specifies the exact
    quantity to be trade and it's send to `ExecutionHandler`.
    */
    class OrderEvent: public Event {
        private:
            vector<Order> orders_;
        public:
            inline explicit OrderEvent(const vector<Order> & orders)
                : Event(EventType::ORDER), orders_(orders) {}

            inline const vector<Order> & orders() const { return orders_; }
    };
}

#endif