#ifndef __SIGNAL_EVENT_H__
#define __SIGNAL_EVENT_H__
#include "Event.h"
#include "data/Bar.h"
#include <string>
#include <chrono>
#include <format>
#include <string_view>
#include <unordered_map>
#include <vector>
#include "data/SignalDirection.h"

using namespace std;
using namespace std::chrono;
using namespace data;

namespace events {
    class Signal {
        private:
            sys_seconds timestamp_;
            string symbol_;
            SignalDirection direction_;
        public:
            Signal(sys_seconds timestamp, const string & symbol, SignalDirection direction):
                timestamp_(timestamp), symbol_(symbol), direction_(direction) {}

            sys_seconds timestamp() const { return timestamp_; }
            const string & symbol() const { return symbol_; }
            SignalDirection direction() const { return direction_; }
            
    };

    /* 
    Represents a trading intention generated by a `Strategy` object.
    It's an advisory signal sent to the `Portfolio`, containing
    the symbol, the timestamp of its generation, and the desired direction.
    */
    class SignalEvent: public Event {    
        private:
            vector<Signal> signals_;
        public:
            inline SignalEvent(const vector<Signal> & signals ):Event(EventType::SIGNAL), signals_(signals){}
            inline SignalEvent(vector<Signal> && signals):Event(EventType::SIGNAL), signals_(std::move(signals)){}
            inline const vector<Signal> & signals() const { return signals_;}
    };
}


#endif