#if !defined(__POSITION_TEST_H__) && defined(__TEST_MAIN__)
#define __POSITION_TEST_H__
#include "portfolio/Portfolio.h"
using namespace std;
using namespace events;

namespace portfolio {
    class PortfolioEventHandlingTest:  public Portfolio {
        public:
            using Portfolio::Portfolio; 

            // `SignalEvent` is generated by `Strategy` and may trigger an `OrderEvent`.
            unique_ptr<Event> process_signal(const SignalEvent & event) override;

            // `FillEvent` is generated by `ExecutionHandler`. It contains the information needed to create or update positions.
            unique_ptr<Event> process_fill(const FillEvent & event) override;

    };

    void portfolio_event_handling_test();

    
}
#endif