#ifdef __TEST_MAIN__
#include "PortfolioTest.h"
#include "events/FillEvent.h"
#include "portfolio/Portfolio.h"
#include "utils/log.h"
#include <cassert>
#include <memory>
#include <unordered_map>
#include <vector>
#include "timeseries/timeseries.h"

using namespace std;

namespace portfolio {
    const string fake_symbol("FAKE");
    const string delusional_symbol("DELUSION");

    // `MarketEvent` is generated by `DataHandler`. It contains bar data used to update the portfolio's equity and positions, and to close positions when necessary.
    EventResponse  PortfolioEventHandlingTest::process_bars(const unordered_map<string, Bar>& bars) {
        assert(bars.contains(fake_symbol));
        const auto & bar = bars.at(fake_symbol);

        assert(
            (long)bar.open_price() == 100L &&
            (long)bar.low_price() == 100L &&
            (long)bar.high_price ()== 100L &&
            (long)bar.close_price() == 100L 
        );

        return nullptr;
    }

    // `SignalEvent` is generated by `Strategy` and may trigger an `OrderEvent`.
    EventResponse  PortfolioEventHandlingTest::process_signal(const SignalEvent & event) {
        assert(event.event_type == EventType::SIGNAL);
        auto const & signals = event.signals();
        assert(signals.size() == 2);

        auto & signal0 = signals[0];
        assert(signal0.symbol() == fake_symbol);
        auto & signal1 = signals[1];
        assert(signal1.symbol() == delusional_symbol);

        return nullptr;
    }

    // `FillEvent` is generated by `ExecutionHandler`. It contains the information needed to create or update positions.
    EventResponse  PortfolioEventHandlingTest::process_fill(const FillEvent & event) {
        assert(event.event_type == EventType::FILL);

        auto const & executions = event.executions();

        auto & execution0 = * executions[0].get();
        assert(execution0.symbol() == fake_symbol);
        assert(execution0.execution_type() == ExecutionType::POSITION_CREATED);
        auto & execution1 = * executions[1].get();
        assert(execution1.symbol() == delusional_symbol);
        assert(execution0.execution_type() == ExecutionType::POSITION_CREATED);

        execution0 = * executions[2].get();
        assert(execution0.symbol() == fake_symbol);
        assert(execution0.execution_type() == ExecutionType::POSITION_CLOSED);
        execution1 = * executions[3].get();
        assert(execution1.symbol() == delusional_symbol);
        assert(execution0.execution_type() == ExecutionType::POSITION_CLOSED);

        return nullptr;
    }

    void portfolio_event_handling_test() {
        PortfolioEventHandlingTest portfolio;

        // Process `MarketEvent` and increment `bar_count`
        unordered_map<string, Bar> bars;
        bars.emplace(fake_symbol, Bar(
            timeseries::sys_seconds_now(),
            fake_symbol,
            100,
            100,
            100,
            100,
            100    
        ));

        MarketEvent market_event(
            bars
        );
        assert(portfolio.bar_count() == 0);
        portfolio.process_event(market_event);
        assert(portfolio.bar_count() == 1);


        // Process `SignalEvent` and increment `signal_count`
        vector<Signal> signals({
            Signal(timeseries::sys_seconds_now(), fake_symbol, SignalDirection::LONG),
            Signal(timeseries::sys_seconds_add_days(timeseries::sys_seconds_now(), 1), delusional_symbol, SignalDirection::SHORT)
        });

        SignalEvent signal_event(signals);
        assert(portfolio.signal_count() == 0);
        portfolio.process_event(signal_event);
        assert(portfolio.signal_count() == 1);

        vector<unique_ptr<Execution>> executions;
        executions.push_back(make_unique<PositionCreatedExecution>(timeseries::sys_seconds_add_days(timeseries::sys_seconds_now(), 2), fake_symbol, 101, 1, 1, SignalDirection::LONG));
        executions.push_back(make_unique<PositionCreatedExecution>(timeseries::sys_seconds_add_days(timeseries::sys_seconds_now(), 3), delusional_symbol, 102, 2, 2, SignalDirection::SHORT));
        executions.push_back(make_unique<PositionClosedExecution>(timeseries::sys_seconds_add_days(timeseries::sys_seconds_now(), 2), fake_symbol, 1, SignalDirection::LONG, 1));
        executions.push_back(make_unique<PositionClosedExecution>(timeseries::sys_seconds_add_days(timeseries::sys_seconds_now(), 3), delusional_symbol, 2, SignalDirection::SHORT, 2));

        assert(portfolio.fill_count() == 0);
        FillEvent fill_event(std::move(executions));
        portfolio.process_event(fill_event);
        assert(portfolio.fill_count() == 1);

        
        cout << "[PASSED] portfolio_event_handling_test" << endl;
    }
}
#endif