#include "timeseries-hurst.h"
#include "operations-span2D.h"
#include "polynomials.h"
#include <cmath>
#include <iostream>

namespace timeseries::hurst {
    std::expected<double, TuxedoError> exponent(
        slice::Span2D & ts // Must be (N,1) or (1,N)
    ) {
        // 1. Calculate the array of standard deviations of the lagged differences
        // var_lagged_diffs computes tau for lags in range(2, max_lag)
        auto tau_exp = operations::span2d::var_lagged_diffs(ts);
        if (!tau_exp.has_value()) {
            return std::unexpected(tau_exp.error());
        }

        auto& tau = tau_exp.value();
        size_t num_lags = tau.rows();

        if (num_lags == 0) {
            return std::unexpected(TuxedoError::ERR_SAMPLE_TOO_SMALL);
        }

        // 2. Prepare the logarithmic arrays for the polynomial fit
        slice::MutableSlice2D log_lags(num_lags, 1);
        slice::MutableSlice2D log_tau(num_lags, 1);

        for (size_t i = 0; i < num_lags; ++i) {
            // Lags generated by var_lagged_diffs start at 2
            double lag = static_cast<double>(i + 2); 
            
            log_lags[i, 0].value() = std::log(lag);
            
            // Extract tau value safely and apply natural log
            auto tau_val = tau[i, 0];
            if (!tau_val.has_value()) {
                return std::unexpected(tau_val.error());
            }
            log_tau[i, 0].value() = std::log(tau_val.value());
        }

        // 3. Use a linear fit (degree 1) to estimate the Hurst Exponent
        // polynomial::fit returns coefficients from highest degree to lowest (e.g. c_1*x + c_0)
        auto poly_exp = polynomials::fit(log_lags, log_tau, 1);
        if (!poly_exp.has_value()) {
            return std::unexpected(poly_exp.error());
        }

        auto& poly = poly_exp.value();
        
        // The slope (Hurst exponent) is the highest degree coefficient (index 0)
        auto hurst_exponent = poly[0, 0];
        if (!hurst_exponent.has_value()) {
            return std::unexpected(hurst_exponent.error());
        }

        return hurst_exponent.value();
    }
}