#!/usr/bin/env python3
from numpy import array, asarray, inf, polyval
from scipy.stats import norm
from statsmodels.tsa import adfvalues
import statsmodels.tsa.stattools as ts
import numpy as np

def mackinnonp_test():
    test_statistics = np.array([-4.5, -2.8, -1.5, 0.0, 1.2])
    regression_types = ("n", "c", "ct", "ctt")

    for reg_type in regression_types:    
        for index in range(1, len(adfvalues.tau_star_nc)+1):
            print(f"{reg_type},{index}: ", end='');

            for stat in test_statistics:
                res = adfvalues.mackinnonp(stat, reg_type, index);
                print(f"{res}, ", end = '')
            print() 

def mackinnoncrit_test():
    regression_types = ("n", "c", "ct", "ctt")
    for reg_type in regression_types:    
        # Retrieve the specific table for this regression type
        tau = adfvalues.tau_2010s[reg_type]
        max_N = tau.shape[0]  # Get the actual number of sequences available
        
        for N in range(1, max_N + 1):
            value = adfvalues.mackinnoncrit(N, regression=reg_type, nobs=5)
            print(f"{reg_type}, N={N}: {value}")


if __name__ == "__main__":
    mackinnoncrit_test()
    # N = 1
    # tau = adfvalues.tau_2010s['ctt']

    # print('tau')
    # print(tau)
    # print()

    # print('tau[N-1, :,::]')
    # print(tau[N-1, :,::])

    # print('tau[N-1, :,:: -1]')
    # print(tau[N-1, :,:: -1])    
    
    # print('tau[N-1, :,:: -1].T')
    # print(tau[N-1, :,:: -1].T)    

    # print('polyval(tau[N-1, :,:: -1].T)')
    # print(polyval(tau[N-1, :,:: -1].T,1))

ts.adfuller