#!/usr/bin/env python3
from numpy import array, asarray, inf, polyval
from scipy.stats import norm
from statsmodels.tsa import adfvalues
import numpy as np

def mackinnonp():
    test_statistics = np.array([-4.5, -2.8, -1.5, 0.0, 1.2])
    regression_types = ("n", "c", "ct", "ctt")

    for reg_type in regression_types:    
        for index in range(1, len(adfvalues.tau_star_nc)+1):
            print(f"{reg_type},{index}: ", end='');

            for stat in test_statistics:
                res = adfvalues.mackinnonp(stat, reg_type, index);
                print(f"{res}, ", end = '')
            print() 


if __name__ == "__main__":
    N = 1
    tau = adfvalues.tau_2010s['ctt']

    print('tau')
    print(tau)
    print()

    print('tau[N-1, :,::]')
    print(tau[N-1, :,::])

    print('tau[N-1, :,:: -1]')
    print(tau[N-1, :,:: -1])    
    
    print('tau[N-1, :,:: -1].T')
    print(tau[N-1, :,:: -1].T)    

    print('polyval(tau[N-1, :,:: -1].T)')
    print(polyval(tau[N-1, :,:: -1].T,1))

    